version: '3.6'
services:
  ui:
    image: joxit/docker-registry-ui:static
    container_name: ui
    restart: always
    ports: 
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./logs:/var/log/nginx
    environment:
      - REGISTRY_TITLE=Private Docker Registry
      - DELETE_IMAGES=true
    secrets:
      - server_ssl_cert
      - server_ssl_key
    networks:
      - registry-ui-net
    depends_on:
      - registry
  registry:
    image: registry:2.7.1
    container_name: registry
    restart: always
    ports: 
      - 5000:5000
    volumes:
      - ./storage:/var/lib/registry
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    networks:
      - registry-ui-net
secrets:
  server_ssl_cert:
    file: ../nginx/certs/server.crt
  server_ssl_key:
    file: ../nginx/certs/server.key
networks:
  registry-ui-net:
